# Generated by Django 4.1.7 on 2023-04-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_owner_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner_permissions',
        ),
    ]
